// Portuguese labels for the persisted field names shown in audit snapshots.
// Keys follow the public contracts; unknown keys fall back to the raw name.
export const fieldLabels: Record<string, string> = {
  // Accounts
  login: 'Login',
  displayName: 'Nome de exibição',
  active: 'Ativo',
  mustChangePassword: 'Troca de senha obrigatória',
  passwordChanged: 'Senha alterada',
  roleCodes: 'Perfis',
  roles: 'Perfis',
  createdAt: 'Criado em',
  updatedAt: 'Atualizado em',
  createdBy: 'Criado por',
  updatedBy: 'Atualizado por',
  recordedBy: 'Lançado por',
  decidedBy: 'Decidido por',
  resolvedBy: 'Resolvido por',
  declaredBy: 'Declarado por',
  requestedBy: 'Solicitado por',
  // Registration
  familyCode: 'Código familiar',
  referencePersonId: 'Pessoa de referência',
  referencePersonName: 'Nome da pessoa de referência',
  referenceMemberId: 'Membro de referência',
  isReference: 'Titular',
  relationshipToReference: 'Parentesco com o titular',
  membershipId: 'Vínculo',
  membershipScope: 'Abrangência do vínculo',
  memberships: 'Vínculos',
  previousMembership: 'Vínculo anterior',
  memberCount: 'Quantidade de membros',
  members: 'Membros',
  currentFamily: 'Família atual',
  sourceFamily: 'Família de origem',
  targetFamily: 'Família de destino',
  targetFamilyId: 'Família de destino',
  validFrom: 'Início da vigência',
  validUntil: 'Fim da vigência',
  effectiveFrom: 'Vigente desde',
  effectiveUntilExclusive: 'Vigente até (exclusivo)',
  effectiveAt: 'Vigência em',
  shoeSize: 'Número do calçado',
  clothingSize: 'Tamanho de roupa',
  informedOn: 'Informado em',
  sizeProfile: 'Tamanhos',
  occupationOrIncomeSource: 'Ocupação ou fonte de renda',
  incomeAmount: 'Renda',
  schoolLevelOrGrade: 'Série ou nível escolar',
  attendsSchool: 'Frequenta a escola',
  worksCurrently: 'Trabalha atualmente',
  studyMode: 'Modalidade de estudo',
  education: 'Escolaridade',
  duplicateReview: 'Análise de duplicidade',
  // Data quality and configuration
  identifiedAt: 'Identificada em',
  resolvedAt: 'Resolvida em',
  resolution: 'Resolução',
  fieldKey: 'Campo',
  fieldKeys: 'Campos',
  selectedFieldKeys: 'Campos selecionados',
  personFields: 'Campos de pessoa',
  familyFields: 'Campos de família',
  decisionReference: 'Referência da decisão',
  decisions: 'Decisões',
  decidedAt: 'Decidido em',
  enabled: 'Habilitado',
  version: 'Versão',
  previousVersionId: 'Versão anterior',
  supersededById: 'Substituída por',
  schemaVersion: 'Versão do esquema',
  // Projects and activities
  description: 'Descrição',
  nature: 'Natureza',
  instituteId: 'Instituto',
  serviceTypeId: 'Tipo de atividade pontual',
  projectId: 'Projeto',
  project: 'Projeto',
  activity: 'Atividade',
  activities: 'Atividades',
  enrollment: 'Inscrição',
  enrollments: 'Inscrições',
  startsOn: 'Início',
  endsOn: 'Fim',
  closedAt: 'Encerrado em',
  plannedSchedule: 'Agenda prevista',
  responsibleId: 'Responsável',
  // Attendance
  session: 'Encontro',
  sessionId: 'Encontro',
  sessionRevision: 'Revisão do encontro',
  attendance: 'Frequência',
  attendances: 'Frequências',
  context: 'Contexto',
  location: 'Localização',
  guestPersonIds: 'Convidados',
  coverageRevisions: 'Revisões de cobertura',
  // Eligibility
  asOf: 'Data de referência',
  evaluatedAt: 'Avaliada em',
  situation: 'Situação da aptidão',
  appliesTo: 'Aplica-se a',
  minimum: 'Mínimo',
  period: 'Período',
  definition: 'Definição',
  rule: 'Regra',
  recessRule: 'Regra de recesso',
  justificationRule: 'Regra de justificativas',
  incompleteEvidenceRule: 'Regra de evidência incompleta',
  newParticipantRule: 'Regra de novos participantes',
  toleranceRule: 'Regra de tolerância',
  opportunityRule: 'Regra de oportunidades',
  qualifyingPersonIds: 'Pessoas que atendem ao critério',
  pendingReason: 'Motivo da pendência',
  // Social form
  socialFormId: 'Ficha social',
  latestForm: 'Última ficha',
  latestPublishedFormId: 'Última ficha publicada',
  correctionOfFormId: 'Corrige a ficha',
  declaredAt: 'Declarado em',
  declaredNeeds: 'Necessidades declaradas',
  declarations: 'Declarações',
  needs: 'Necessidades',
  hasNeeds: 'Possui necessidades',
  otherNeed: 'Outra necessidade',
  observations: 'Observações',
  hasObservations: 'Possui observações',
  acknowledgement: 'Ciência em papel',
  acknowledgedOn: 'Ciência em',
  beneficiarySigned: 'Assinatura do beneficiário',
  registrationResponsibleName: 'Responsável pelo cadastro',
  registrationResponsibleSigned: 'Assinatura do responsável pelo cadastro',
  familySnapshot: 'Dados da família na ficha',
  personSnapshot: 'Dados da pessoa na ficha',
  relationshipSnapshot: 'Parentesco na ficha',
  sizeSnapshot: 'Tamanhos na ficha',
  housing: 'Moradia',
  housingTenure: 'Situação do imóvel',
  dwellingType: 'Tipo de moradia',
  construction: 'Construção',
  floorType: 'Tipo de piso',
  roomCount: 'Quantidade de cômodos',
  bedroomCount: 'Quantidade de quartos',
  electricity: 'Energia elétrica',
  waterSupply: 'Abastecimento de água',
  waterTreatment: 'Tratamento da água',
  sewage: 'Esgoto',
  wasteDisposal: 'Destino do lixo',
  transportation: 'Transporte',
  riskArea: 'Área de risco',
  economy: 'Economia',
  governmentBenefitName: 'Benefício governamental',
  receivesGovernmentBenefit: 'Recebe benefício governamental',
  generalCondition: 'Condição geral',
  hygiene: 'Higiene',
  health: 'Saúde',
  healthUnit: 'Unidade de saúde',
  hasHealthUnit: 'Possui unidade de saúde',
  hasCommunityHealthAgent: 'Possui agente comunitário de saúde',
  communityHealthAgent: 'Agente comunitário de saúde',
  physicalHealth: 'Saúde física',
  physicalHealthProblems: 'Problemas de saúde física',
  hasPhysicalHealthProblems: 'Possui problemas de saúde física',
  spiritualHealth: 'Saúde espiritual',
  otherSpiritualHealth: 'Outra condição espiritual',
  medications: 'Medicamentos',
  religion: 'Religião',
  participatesInEvangelization: 'Participa da evangelização',
  declaredChildCount: 'Crianças declaradas',
  declaredAdolescentCount: 'Adolescentes declarados',
  declaredWorkerCount: 'Trabalhadores declarados',
  declaredPensionerCount: 'Aposentados ou pensionistas declarados',
  options: 'Opções',
  label: 'Rótulo',
  isOther: 'Outra opção',
  required: 'Obrigatório',
  purpose: 'Finalidade',
  relevance: 'Relevância',
  text: 'Texto',
};
